name: Check Results

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:       # Also allow manual run

jobs:
  run-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Needed for push to work

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run result checker
        run: python satta_result_checker.py

      - name: Commit updated CSV if changed
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "GitHub Bot"
          git add enhanced_satta_data.csv accuracy_log.csv
          git diff --cached --quiet || (
            git commit -m "Auto update results CSV"
            git push
          )
