name: Satta ML Predictions

on:
  schedule:
    - cron: '*/15 0-18 * * *'  # Every 15 minutes from 12:00 AM to 6:45 PM UTC (IST 5:30 AM – 11:59 PM)
  workflow_dispatch:

jobs:
  run-predict:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run predict script
        run: python predict.py
