name: Satta Prediction

on:
  schedule:
    - cron: '18 19 * * *'  # Runs daily at 12:18 AM IST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas numpy scikit-learn beautifulsoup4 requests

      - name: Run script
        run: python predict.py

      - name: Commit updated CSVs
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add satta_data.csv prediction_log.csv daily_prediction.txt
          git commit -m 'Auto: Update predictions and learning log' || echo "No changes"
          git push
